// <auto-generated />
using System;
using DigitalFormsSystem.Core.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DigitalFormsSystem.Core.Migrations
{
    [DbContext(typeof(DigitalFormsSystemContext))]
    [Migration("20260825030934_AddDamagedReportFollowUps")]
    partial class AddDamagedReportFollowUps
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DigitalFormsSystem.Core.Models.AssetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id")
                        .HasName("PK__AssetTyp__3214EC27F8985D91");

                    b.HasIndex(new[] { "AssetTypeName" }, "UQ__AssetTyp__6824772C5E2EF8A2")
                        .IsUnique();

                    b.ToTable("AssetTypes");
                });

            modelBuilder.Entity("DigitalFormsSystem.Core.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("DigitalFormsSystem.Core.Models.DamagedReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("AdministrativeDiscipline")
                        .HasColumnType("bit");

                    b.Property<string>("BrandSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CauseOfDamage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ControlNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("DatePurchased")
                        .HasColumnType("date");

                    b.Property<string>("Findings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FixedAssetCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImmediateAction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("IncidentDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InvestigatedByEmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NegligenceDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NegligenceFlag")
                        .HasColumnType("int");

                    b.Property<int?>("NotedByEmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("ReceivedByEmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReceivedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Recommendation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecommendedAction")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReportedByEmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("RequestStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VerifiedByEmployeeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InvestigatedByEmployeeId");

                    b.HasIndex("NotedByEmployeeId");

                    b.HasIndex("ReceivedByEmployeeId");

                    b.HasIndex("ReportedByEmployeeId");

                    b.HasIndex("VerifiedByEmployeeId");

                    b.ToTable("DamagedReports");
                });

            modelBuilder.Entity("DigitalFormsSystem.Core.Models.DamagedReportFollowUp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DamagedReportId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FollowUpDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NotedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DamagedReportId");

                    b.ToTable("DamagedReportFollowUps");
                });

            modelBuilder.Entity("DigitalFormsSystem.Core.Models.DamagedReportImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DamagedReportId")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DamagedReportId");

                    b.ToTable("DamagedReportImages");
                });

            modelBuilder.Entity("DigitalFormsSystem.Core.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Company")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly?>("DateHired")
                        .HasColumnType("date");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EmployeeNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsFirstLogin")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Status")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.HasKey("Id")
                        .HasName("PK__Employee__3214EC270C6F6526");

                    b.HasIndex(new[] { "Department" }, "IX_Employees_Department");

                    b.HasIndex(new[] { "EmployeeNo" }, "IX_Employees_EmployeeNo");

                    b.HasIndex(new[] { "EmployeeNo" }, "UQ__Employee__7AD0F1B749DF82FF")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("DigitalFormsSystem.Core.Models.ExistingUnitDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FixedAssetRequestId")
                        .HasColumnType("int")
                        .HasColumnName("FixedAssetRequestID");

                    b.Property<int>("ItemNo")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("UserName")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id")
                        .HasName("PK__Existing__3214EC27CE005FA4");

                    b.HasIndex("FixedAssetRequestId");

                    b.ToTable("ExistingUnitDetails");
                });

            modelBuilder.Entity("DigitalFormsSystem.Core.Models.FixedAssetPrintLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FixedAssetRequestId")
                        .HasColumnType("int")
                        .HasColumnName("FixedAssetRequestID");

                    b.Property<string>("Ipaddress")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("IPAddress");

                    b.Property<DateTime?>("PrintDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PrintFormat")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Full Form");

                    b.Property<int>("PrintedByEmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("PrintedByEmployeeID");

                    b.Property<string>("Remarks")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id")
                        .HasName("PK__FixedAss__3214EC27840E0AAA");

                    b.HasIndex("FixedAssetRequestId");

                    b.HasIndex("PrintedByEmployeeId");

                    b.ToTable("FixedAssetPrintLogs");
                });

            modelBuilder.Entity("DigitalFormsSystem.Core.Models.FixedAssetRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetType")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("AssetTypeId")
                        .HasColumnType("int")
                        .HasColumnName("AssetTypeID");

                    b.Property<string>("ControlNo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("DamagedReportNo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateOnly>("DateRequested")
                        .HasColumnType("date");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DetailedDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstimatedLifeSpan")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("EvaluatedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("EvaluatedByEmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("EvaluatedByEmployeeID");

                    b.Property<string>("EvaluatedByName")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("ExistingUnitCount")
                        .HasColumnType("int");

                    b.Property<string>("ExistingUser")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ProposedLocation")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("ReasonPurpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("Draft");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("RequestedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("RequestedByEmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("RequestedByEmployeeID");

                    b.Property<string>("RequestedByName")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateOnly>("TargetDateNeeded")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__FixedAss__3214EC27F65086B2");

                    b.HasIndex("AssetTypeId");

                    b.HasIndex("EvaluatedByEmployeeId");

                    b.HasIndex("RequestedByEmployeeId");

                    b.HasIndex(new[] { "ControlNo" }, "IX_FixedAssetRequests_ControlNo");

                    b.HasIndex(new[] { "DateRequested" }, "IX_FixedAssetRequests_DateRequested");

                    b.HasIndex(new[] { "Department" }, "IX_FixedAssetRequests_Department");

                    b.HasIndex(new[] { "RequestStatus" }, "IX_FixedAssetRequests_RequestStatus");

                    b.HasIndex(new[] { "ControlNo" }, "UQ__FixedAss__091DC38FA5A637C2")
                        .IsUnique()
                        .HasFilter("[ControlNo] IS NOT NULL");

                    b.ToTable("FixedAssetRequests");
                });

            modelBuilder.Entity("DigitalFormsSystem.Core.Models.FixedAssetRequestApproval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AmortizationMonths")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("ExecutiveEvaluatedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("ExecutiveEvaluatedByEmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("ExecutiveEvaluatedByEmployeeID");

                    b.Property<bool?>("ExecutiveRecommendingApproval")
                        .HasColumnType("bit");

                    b.Property<string>("ExecutiveRemarks")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FinanceProcessedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("FinanceProcessedByEmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("FinanceProcessedByEmployeeID");

                    b.Property<string>("FinanceRemarks")
                        .HasColumnType("text");

                    b.Property<string>("FixedAssetCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("FixedAssetRequestId")
                        .HasColumnType("int")
                        .HasColumnName("FixedAssetRequestID");

                    b.Property<bool?>("IsCapitalized")
                        .HasColumnType("bit");

                    b.Property<bool?>("PresidentApproved")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PresidentApprovedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("PresidentApprovedByEmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("PresidentApprovedByEmployeeID");

                    b.Property<string>("PresidentRemarks")
                        .HasColumnType("text");

                    b.Property<decimal?>("Quotation1Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Quotation1Reference")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal?>("Quotation2Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Quotation2Reference")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("ReceivedByEmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("ReceivedByEmployeeID");

                    b.Property<DateOnly?>("ReceivedDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("Vpapproved")
                        .HasColumnType("bit")
                        .HasColumnName("VPApproved");

                    b.Property<DateTime?>("VpapprovedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("VPApprovedAt");

                    b.Property<int?>("VpapprovedByEmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("VPApprovedByEmployeeID");

                    b.Property<string>("Vpremarks")
                        .HasColumnType("text")
                        .HasColumnName("VPRemarks");

                    b.HasKey("Id")
                        .HasName("PK__FixedAss__3214EC2767ABA27B");

                    b.HasIndex("ExecutiveEvaluatedByEmployeeId");

                    b.HasIndex("FinanceProcessedByEmployeeId");

                    b.HasIndex("PresidentApprovedByEmployeeId");

                    b.HasIndex("ReceivedByEmployeeId");

                    b.HasIndex("VpapprovedByEmployeeId");

                    b.HasIndex(new[] { "FixedAssetRequestId" }, "IX_FixedAssetRequestApprovals_FixedAssetRequestID");

                    b.ToTable("FixedAssetRequestApprovals");
                });

            modelBuilder.Entity("DigitalFormsSystem.Core.Models.FixedAssetTransferHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("FixedAssetCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FromDepartment")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("FromEmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("FromEmployeeID");

                    b.Property<string>("FromSection")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("ProcessedByEmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("ProcessedByEmployeeID");

                    b.Property<string>("ToDepartment")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("ToEmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("ToEmployeeID");

                    b.Property<string>("ToSection")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateOnly>("TransferDate")
                        .HasColumnType("date");

                    b.Property<string>("TransferReason")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("PK__FixedAss__3214EC27B06C25E6");

                    b.HasIndex("FromEmployeeId");

                    b.HasIndex("ProcessedByEmployeeId");

                    b.HasIndex("ToEmployeeId");

                    b.ToTable("FixedAssetTransferHistory", (string)null);
                });

            modelBuilder.Entity("DigitalFormsSystem.Core.Models.MemorandumReceipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("Ccfinance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("CCFinance");

                    b.Property<bool?>("Ccpurchasing")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("CCPurchasing");

                    b.Property<bool?>("CcrequestingDept")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("CCRequestingDept");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FixedAssetCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("FixedAssetRequestId")
                        .HasColumnType("int")
                        .HasColumnName("FixedAssetRequestID");

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ModelNumber")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateOnly?>("Podate")
                        .HasColumnType("date")
                        .HasColumnName("PODate");

                    b.Property<string>("Ponumber")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("PONumber");

                    b.Property<int>("ReceivedByEmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("ReceivedByEmployeeID");

                    b.Property<string>("ReceivedByName")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<DateOnly>("ReceivedDate")
                        .HasColumnType("date");

                    b.Property<string>("ReceivedSignature")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("ReleasedByEmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("ReleasedByEmployeeID");

                    b.Property<string>("ReleasedByName")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<DateOnly>("ReleasedDate")
                        .HasColumnType("date");

                    b.Property<string>("ReleasedSignature")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Section")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TransactionType")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Memorand__3214EC277729DE94");

                    b.HasIndex("FixedAssetRequestId");

                    b.HasIndex("ReceivedByEmployeeId");

                    b.HasIndex("ReleasedByEmployeeId");

                    b.ToTable("MemorandumReceipt", (string)null);
                });

            modelBuilder.Entity("DigitalFormsSystem.Core.Models.RequestStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("ChangedByEmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("ChangedByEmployeeID");

                    b.Property<int>("FixedAssetRequestId")
                        .HasColumnType("int")
                        .HasColumnName("FixedAssetRequestID");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("OldStatus")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("PK__RequestS__3214EC27B134BA8C");

                    b.HasIndex("ChangedByEmployeeId");

                    b.HasIndex("FixedAssetRequestId");

                    b.ToTable("RequestStatusHistory", (string)null);
                });

            modelBuilder.Entity("DigitalFormsSystem.Core.Models.VwFixedAssetRequestCompletePrint", b =>
                {
                    b.Property<int?>("AmortizationMonths")
                        .HasColumnType("int");

                    b.Property<string>("AssetClassification")
                        .IsRequired()
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("AssetType")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ControlNo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("DamagedReportNo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateOnly>("DateRequested")
                        .HasColumnType("date");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DetailedDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstimatedLifeSpan")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("EvaluatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("EvaluatedByName")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("ExecutiveEvaluatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("ExecutiveEvaluatedByName")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ExecutiveRecommendation")
                        .IsRequired()
                        .HasMaxLength(19)
                        .IsUnicode(false)
                        .HasColumnType("varchar(19)");

                    b.Property<string>("ExecutiveRemarks")
                        .HasColumnType("text");

                    b.Property<int?>("ExistingUnitCount")
                        .HasColumnType("int");

                    b.Property<string>("ExistingUser")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("FinanceProcessedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("FinanceProcessedByName")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("FinanceRemarks")
                        .HasColumnType("text");

                    b.Property<string>("FixedAssetCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("MemorandumItemDescription")
                        .HasColumnType("text");

                    b.Property<string>("MemorandumReceivedByName")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<DateOnly?>("MemorandumReceivedDate")
                        .HasColumnType("date");

                    b.Property<string>("ModelNumber")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateOnly?>("Podate")
                        .HasColumnType("date")
                        .HasColumnName("PODate");

                    b.Property<string>("Ponumber")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("PONumber");

                    b.Property<string>("PresidentApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)");

                    b.Property<DateTime?>("PresidentApprovedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("PresidentApprovedByName")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PresidentRemarks")
                        .HasColumnType("text");

                    b.Property<string>("ProposedLocation")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal?>("Quotation1Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Quotation1Reference")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal?>("Quotation2Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Quotation2Reference")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ReasonPurpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReceivedByName")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<DateOnly?>("ReceivedDate")
                        .HasColumnType("date");

                    b.Property<string>("ReleasedByName")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<DateOnly?>("ReleasedDate")
                        .HasColumnType("date");

                    b.Property<string>("RequestStatus")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("RequestedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("RequestedByName")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateOnly>("TargetDateNeeded")
                        .HasColumnType("date");

                    b.Property<string>("TransactionType")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("VpapprovalStatus")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("VPApprovalStatus");

                    b.Property<DateTime?>("VpapprovedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("VPApprovedAt");

                    b.Property<string>("VpapprovedByName")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("VPApprovedByName");

                    b.Property<string>("Vpremarks")
                        .HasColumnType("text")
                        .HasColumnName("VPRemarks");

                    b.ToTable((string)null);

                    b.ToView("vw_FixedAssetRequest_CompletePrint", (string)null);
                });

            modelBuilder.Entity("DigitalFormsSystem.Core.Models.AuditLog", b =>
                {
                    b.HasOne("DigitalFormsSystem.Core.Models.Employee", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DigitalFormsSystem.Core.Models.DamagedReport", b =>
                {
                    b.HasOne("DigitalFormsSystem.Core.Models.Employee", "InvestigatedByEmployee")
                        .WithMany()
                        .HasForeignKey("InvestigatedByEmployeeId");

                    b.HasOne("DigitalFormsSystem.Core.Models.Employee", "NotedByEmployee")
                        .WithMany()
                        .HasForeignKey("NotedByEmployeeId");

                    b.HasOne("DigitalFormsSystem.Core.Models.Employee", "ReceivedByEmployee")
                        .WithMany()
                        .HasForeignKey("ReceivedByEmployeeId");

                    b.HasOne("DigitalFormsSystem.Core.Models.Employee", "ReportedByEmployee")
                        .WithMany()
                        .HasForeignKey("ReportedByEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalFormsSystem.Core.Models.Employee", "VerifiedByEmployee")
                        .WithMany()
                        .HasForeignKey("VerifiedByEmployeeId");

                    b.Navigation("InvestigatedByEmployee");

                    b.Navigation("NotedByEmployee");

                    b.Navigation("ReceivedByEmployee");

                    b.Navigation("ReportedByEmployee");

                    b.Navigation("VerifiedByEmployee");
                });

            modelBuilder.Entity("DigitalFormsSystem.Core.Models.DamagedReportFollowUp", b =>
                {
                    b.HasOne("DigitalFormsSystem.Core.Models.DamagedReport", "DamagedReport")
                        .WithMany("FollowUps")
                        .HasForeignKey("DamagedReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DamagedReport");
                });

            modelBuilder.Entity("DigitalFormsSystem.Core.Models.DamagedReportImage", b =>
                {
                    b.HasOne("DigitalFormsSystem.Core.Models.DamagedReport", "DamagedReport")
                        .WithMany("Images")
                        .HasForeignKey("DamagedReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DamagedReport");
                });

            modelBuilder.Entity("DigitalFormsSystem.Core.Models.ExistingUnitDetail", b =>
                {
                    b.HasOne("DigitalFormsSystem.Core.Models.FixedAssetRequest", "FixedAssetRequest")
                        .WithMany("ExistingUnitDetails")
                        .HasForeignKey("FixedAssetRequestId")
                        .IsRequired()
                        .HasConstraintName("FK__ExistingU__Fixed__5535A963");

                    b.Navigation("FixedAssetRequest");
                });

            modelBuilder.Entity("DigitalFormsSystem.Core.Models.FixedAssetPrintLog", b =>
                {
                    b.HasOne("DigitalFormsSystem.Core.Models.FixedAssetRequest", "FixedAssetRequest")
                        .WithMany("FixedAssetPrintLogs")
                        .HasForeignKey("FixedAssetRequestId")
                        .IsRequired()
                        .HasConstraintName("FK__FixedAsse__Fixed__628FA481");

                    b.HasOne("DigitalFormsSystem.Core.Models.Employee", "PrintedByEmployee")
                        .WithMany("FixedAssetPrintLogs")
                        .HasForeignKey("PrintedByEmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK__FixedAsse__Print__6383C8BA");

                    b.Navigation("FixedAssetRequest");

                    b.Navigation("PrintedByEmployee");
                });

            modelBuilder.Entity("DigitalFormsSystem.Core.Models.FixedAssetRequest", b =>
                {
                    b.HasOne("DigitalFormsSystem.Core.Models.AssetType", "AssetTypeNavigation")
                        .WithMany("FixedAssetRequests")
                        .HasForeignKey("AssetTypeId")
                        .HasConstraintName("FK__FixedAsse__Asset__4316F928");

                    b.HasOne("DigitalFormsSystem.Core.Models.Employee", "EvaluatedByEmployee")
                        .WithMany("FixedAssetRequestEvaluatedByEmployees")
                        .HasForeignKey("EvaluatedByEmployeeId")
                        .HasConstraintName("FK__FixedAsse__Evalu__45F365D3");

                    b.HasOne("DigitalFormsSystem.Core.Models.Employee", "RequestedByEmployee")
                        .WithMany("FixedAssetRequestRequestedByEmployees")
                        .HasForeignKey("RequestedByEmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK__FixedAsse__Reque__44FF419A");

                    b.Navigation("AssetTypeNavigation");

                    b.Navigation("EvaluatedByEmployee");

                    b.Navigation("RequestedByEmployee");
                });

            modelBuilder.Entity("DigitalFormsSystem.Core.Models.FixedAssetRequestApproval", b =>
                {
                    b.HasOne("DigitalFormsSystem.Core.Models.Employee", "ExecutiveEvaluatedByEmployee")
                        .WithMany("FixedAssetRequestApprovalExecutiveEvaluatedByEmployees")
                        .HasForeignKey("ExecutiveEvaluatedByEmployeeId")
                        .HasConstraintName("FK__FixedAsse__Execu__4D94879B");

                    b.HasOne("DigitalFormsSystem.Core.Models.Employee", "FinanceProcessedByEmployee")
                        .WithMany("FixedAssetRequestApprovalFinanceProcessedByEmployees")
                        .HasForeignKey("FinanceProcessedByEmployeeId")
                        .HasConstraintName("FK__FixedAsse__Finan__5070F446");

                    b.HasOne("DigitalFormsSystem.Core.Models.FixedAssetRequest", "FixedAssetRequest")
                        .WithMany("FixedAssetRequestApprovals")
                        .HasForeignKey("FixedAssetRequestId")
                        .IsRequired()
                        .HasConstraintName("FK__FixedAsse__Fixed__4BAC3F29");

                    b.HasOne("DigitalFormsSystem.Core.Models.Employee", "PresidentApprovedByEmployee")
                        .WithMany("FixedAssetRequestApprovalPresidentApprovedByEmployees")
                        .HasForeignKey("PresidentApprovedByEmployeeId")
                        .HasConstraintName("FK__FixedAsse__Presi__4F7CD00D");

                    b.HasOne("DigitalFormsSystem.Core.Models.Employee", "ReceivedByEmployee")
                        .WithMany("FixedAssetRequestApprovalReceivedByEmployees")
                        .HasForeignKey("ReceivedByEmployeeId")
                        .HasConstraintName("FK__FixedAsse__Recei__4CA06362");

                    b.HasOne("DigitalFormsSystem.Core.Models.Employee", "VpapprovedByEmployee")
                        .WithMany("FixedAssetRequestApprovalVpapprovedByEmployees")
                        .HasForeignKey("VpapprovedByEmployeeId")
                        .HasConstraintName("FK__FixedAsse__VPApp__4E88ABD4");

                    b.Navigation("ExecutiveEvaluatedByEmployee");

                    b.Navigation("FinanceProcessedByEmployee");

                    b.Navigation("FixedAssetRequest");

                    b.Navigation("PresidentApprovedByEmployee");

                    b.Navigation("ReceivedByEmployee");

                    b.Navigation("VpapprovedByEmployee");
                });

            modelBuilder.Entity("DigitalFormsSystem.Core.Models.FixedAssetTransferHistory", b =>
                {
                    b.HasOne("DigitalFormsSystem.Core.Models.Employee", "FromEmployee")
                        .WithMany("FixedAssetTransferHistoryFromEmployees")
                        .HasForeignKey("FromEmployeeId")
                        .HasConstraintName("FK__FixedAsse__FromE__6D0D32F4");

                    b.HasOne("DigitalFormsSystem.Core.Models.Employee", "ProcessedByEmployee")
                        .WithMany("FixedAssetTransferHistoryProcessedByEmployees")
                        .HasForeignKey("ProcessedByEmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK__FixedAsse__Proce__6EF57B66");

                    b.HasOne("DigitalFormsSystem.Core.Models.Employee", "ToEmployee")
                        .WithMany("FixedAssetTransferHistoryToEmployees")
                        .HasForeignKey("ToEmployeeId")
                        .HasConstraintName("FK__FixedAsse__ToEmp__6E01572D");

                    b.Navigation("FromEmployee");

                    b.Navigation("ProcessedByEmployee");

                    b.Navigation("ToEmployee");
                });

            modelBuilder.Entity("DigitalFormsSystem.Core.Models.MemorandumReceipt", b =>
                {
                    b.HasOne("DigitalFormsSystem.Core.Models.FixedAssetRequest", "FixedAssetRequest")
                        .WithMany("MemorandumReceipts")
                        .HasForeignKey("FixedAssetRequestId")
                        .IsRequired()
                        .HasConstraintName("FK__Memorandu__Fixed__59063A47");

                    b.HasOne("DigitalFormsSystem.Core.Models.Employee", "ReceivedByEmployee")
                        .WithMany("MemorandumReceiptReceivedByEmployees")
                        .HasForeignKey("ReceivedByEmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK__Memorandu__Recei__5AEE82B9");

                    b.HasOne("DigitalFormsSystem.Core.Models.Employee", "ReleasedByEmployee")
                        .WithMany("MemorandumReceiptReleasedByEmployees")
                        .HasForeignKey("ReleasedByEmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK__Memorandu__Relea__5BE2A6F2");

                    b.Navigation("FixedAssetRequest");

                    b.Navigation("ReceivedByEmployee");

                    b.Navigation("ReleasedByEmployee");
                });

            modelBuilder.Entity("DigitalFormsSystem.Core.Models.RequestStatusHistory", b =>
                {
                    b.HasOne("DigitalFormsSystem.Core.Models.Employee", "ChangedByEmployee")
                        .WithMany("RequestStatusHistories")
                        .HasForeignKey("ChangedByEmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK__RequestSt__Chang__693CA210");

                    b.HasOne("DigitalFormsSystem.Core.Models.FixedAssetRequest", "FixedAssetRequest")
                        .WithMany("RequestStatusHistories")
                        .HasForeignKey("FixedAssetRequestId")
                        .IsRequired()
                        .HasConstraintName("FK__RequestSt__Fixed__68487DD7");

                    b.Navigation("ChangedByEmployee");

                    b.Navigation("FixedAssetRequest");
                });

            modelBuilder.Entity("DigitalFormsSystem.Core.Models.AssetType", b =>
                {
                    b.Navigation("FixedAssetRequests");
                });

            modelBuilder.Entity("DigitalFormsSystem.Core.Models.DamagedReport", b =>
                {
                    b.Navigation("FollowUps");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("DigitalFormsSystem.Core.Models.Employee", b =>
                {
                    b.Navigation("FixedAssetPrintLogs");

                    b.Navigation("FixedAssetRequestApprovalExecutiveEvaluatedByEmployees");

                    b.Navigation("FixedAssetRequestApprovalFinanceProcessedByEmployees");

                    b.Navigation("FixedAssetRequestApprovalPresidentApprovedByEmployees");

                    b.Navigation("FixedAssetRequestApprovalReceivedByEmployees");

                    b.Navigation("FixedAssetRequestApprovalVpapprovedByEmployees");

                    b.Navigation("FixedAssetRequestEvaluatedByEmployees");

                    b.Navigation("FixedAssetRequestRequestedByEmployees");

                    b.Navigation("FixedAssetTransferHistoryFromEmployees");

                    b.Navigation("FixedAssetTransferHistoryProcessedByEmployees");

                    b.Navigation("FixedAssetTransferHistoryToEmployees");

                    b.Navigation("MemorandumReceiptReceivedByEmployees");

                    b.Navigation("MemorandumReceiptReleasedByEmployees");

                    b.Navigation("RequestStatusHistories");
                });

            modelBuilder.Entity("DigitalFormsSystem.Core.Models.FixedAssetRequest", b =>
                {
                    b.Navigation("ExistingUnitDetails");

                    b.Navigation("FixedAssetPrintLogs");

                    b.Navigation("FixedAssetRequestApprovals");

                    b.Navigation("MemorandumReceipts");

                    b.Navigation("RequestStatusHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
